'use client'
import {Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import {CartContext} from './_context/CartContext'
import { useState } from "react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],weight:"700"
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart, setCart,updateSelectedPrice] = useState([])
  return (
    <ClerkProvider>
      <CartContext.Provider value={{cart,setCart,updateSelectedPrice}}>
    <html lang="en">
      <body
        className={` ${geistMono.variable} antialiased`}
      >
        <Header />
        <SignedOut>
            </SignedOut>
            <SignedIn>
            </SignedIn>
        {children}
        <Footer />
      </body>
    </html>
    </CartContext.Provider>
    </ClerkProvider>
  );
}
